{{- if .Values.backend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "task-platform.backend.fullname" . }}
  labels:
    {{- include "task-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "task-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}

